env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - jest-dom
  - testing-library
  - import
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
ignorePatterns:
  - vite.config.ts
  - vitest.setup.ts
settings:
  import/resolver:
    typescript: []
rules:
  react/react-in-jsx-scope: off
  semi:
    - error
    - never
  arrow-body-style: 0
  import/prefer-default-export: off
  import/no-default-export: error
  react/function-component-definition:
    - warn
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps:
    - warn
  react/require-default-props: off
  react/jsx-props-no-spreading: off
  react/jsx-no-useless-fragment: off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-unused-expressions': off
